errors occured with new class: Error Traceback (most recent call last):   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor     yield   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run     testMethod()   File "/Users/admin/Downloads/Python-Automation/training-barantsev/git/tests/test_add_new_contact.py", line 102, in test_add_new_contact     self.fill_first_last_name(wd, ContactFormAttributes(firstname="elena", middlename="test", lastname="lastname")) TypeError: __init__() missing 10 required positional arguments: 'nickname', 'title', 'company', 'address', 'mobile', 'email', 'byear', 'phone2', 'notes', and 'address2'